defaultName: TimeIT Server

mailserver: localhost

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  #driverClass: org.postgresql.Driver
  #driverClass: org.mariadb.jdbc.Driver
  # the username
  user: timeit
  # the password
  password: password

  # the JDBC URL
  url: jdbc:h2:~/.timeit_database
  #url: jdbc:postgresql://localhost:5432/timeitdb
  #url: jdbc:mariadb://localhost:3306/timeitdb
