defaultName: TimeIT Server

mailserver: localhost

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  #driverClass: org.postgresql.Driver
  #driverClass: org.mariadb.jdbc.Driver
  # the username
  user:
  # the password
  password:

  # the JDBC URL
  url: jdbc:h2:~/.timeit_database
  #url: jdbc:postgresql://localhost:5432/timeitdb
  #url: jdbc:mariadb://localhost:3306/timeitdb

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: ./server.keystore
      keyStorePassword: password
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: ./server.keystore
      keyStorePassword: password
      validateCerts: false
